# voting-app-stable-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app-stable-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
selector:
  matchLabels:
    app: {{ include "voting-app-stable-chart.name" . }}
    release: {{ .Release.Name }}
template:
  metadata:
    labels:
      app: {{ include "voting-app-stable-chart.name" . }}
      release: {{ .Release.Name }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ include "voting-app-stable-chart.name" . }}
    release: {{ .Release.Name }}
ports:
  - port: {{ .Values.service.port }}
    targetPort: http
  type: {{ .Values.service.type }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "voting-app-stable-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.hosts[20.74.48.7].host }}
    http:
      paths:
  - pathType: Prefix
    path: "/"
      backend:
        service:
          name: {{ .Values.service.name }}
          port:
            number: {{ .Values.service.port }}
{{- end }}
