name: canary CI/CD

#on:
#  push:
#    branches:
#      - main

#jobs:
#  terraform:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v3

#    - name: Login to Azure
#      run: az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

#    - name: Set up Terraform
#      uses: hashicorp/setup-terraform@v1

#    - name: Setup Python
#      uses: actions/setup-python@v3
#      with:
#        python-version: latest

#    - name: Install Azure CLI
#      run: pip install azure-cli

#    - name: Terraform Init
#      run: terraform init

#    - name: Terraform Validate
#      run: terraform validate

#    - name: Terraform Plan
#      run: terraform plan 

#    - name: Terraform Apply
#      if: github.event == 'push'
#      run: terraform apply 

#      name: CI/CD Pipeline


on:
  push:
    branches:
      - main

jobs:
  deploy_stable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy Stable
      run: |
        helm upgrade --install voting-app-stable voting-app-stable-chart \
          --set ingress.enabled=true \
          --set ingress.hosts[0].host=voting-app.20.74.48.7 \
          --set replicaCount=3

  deploy_canary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy Canary
      run: |
        helm upgrade --install voting-app-canary voting-app-canary-chart \
          --set ingress.enabled=true \
          --set ingress.hosts[0].host=voting-app-canary.20.74.48.7 \
          --set replicaCount=3
